language: rust
rust:
  - nightly

arch:
  - amd64
  - arm64

matrix:
  include:
    - os: osx
      arch: amd64
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64

compiler:
  - clang

script:
  - cargo +nightly test --verbose
  - cargo +nightly test --verbose --release